apiVersion: v1
kind: Service
metadata:
    name: "kishkube"
    labels:
        app: "kishkube"
spec:
    type: LoadBalancer
    ports:
    - port: 44123
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "kishkube"