on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kishreg.azurecr.io
        username: ${{ secrets.acr_kishreg_username }}
        password: ${{ secrets.acr_kishreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t kishreg.azurecr.io/kishkube:${{ github.sha }}
        docker push kishreg.azurecr.io/kishkube:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kishkube_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kishkubed34c | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kishkubed34c`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kishkubed34c
        container-registry-url: kishreg.azurecr.io
        container-registry-username: ${{ secrets.acr_kishreg_username }}
        container-registry-password: ${{ secrets.acr_kishreg_password }}
        secret-name: kishkubedockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: kishkubed34c
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          kishreg.azurecr.io/kishkube:${{ github.sha }}
        imagepullsecrets: |
          kishkubedockerauth